#gradle things
org.gradle.parallel=true
org.gradle.caching=true
systemProp.http.userAgent=Gradle
org.gradle.jvmargs=-Xmx6g -XX:+UseG1GC -XX:+ParallelRefProcEnabled

# Option 1: Local Directory (build/repo)
# Ideal for a subsequent git commit + push to a branch served via raw.githubusercontent.com
# publishing_url=

# Option 2: GitHub Packages (example)
# publishing_url=https://maven.pkg.github.com/Akfz/DBuild
# publishing_username=YOUR_GITHUB_USERNAME
# publishing_password=YOUR_GITHUB_TOKEN

# Option 3: Custom Server / Nexus / Artifactory
# publishing_url=https://your-maven-server.com/releases
# publishing_username=admin
# publishing_password=secret

#aslib gitversion (you can change to "Dev_1.20.1-SNAPSHOT", for last versions or set Release_1.20.1-SNAPSHOT for stab version)
#Uncomment aslib_version to use, AsLib -> https://github.com/Akfz/AsLib
#aslib_version=Release_1.20.1-SNAPSHOT
dbuild_version=1.0-SNAPSHOT

#mod meta
mod_id=temp
mod_version=1.0-SNAPSHOT
mod_name=DBuildTemplate
mod_description=ChangeME!
mod_authors=Akaize
mod_license=Change this
mod_homepage=https://github.com/Akfz/DBuild
mod_issues=
mod_icon=assets/temp/icon.png

maven_group=com.template
archives_base_name=temp
#you need to rename for work mixins
mixin_name=template.mixins

#minecraft data
java_version=17
minecraft_version=1.20.1

#mappings
mojang_mappings=1.20.1
parchment_mc_version=1.20.1
parchment_version=2023.09.03

#loaders settings
fabric_loom_version=1.13-SNAPSHOT
fabric_loader_version=0.15.11

forge_version=1.20.1-47.4.20
forge_gradle_version=6.0.53

neoforge_version=20.4.251
neoforge_gradle_version=2.0.78

#mixin
mixin_version=0.8.7
mixingradle_version=0.7-SNAPSHOT
mixinextras_version=0.4.1