modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="temp"
version="1.0.0"
displayName="Unnamed Mod"
logoFile="icon.png"
authors="Akfz"
description='''A template multiloader mod'''

[[mixins]]
config="temp.mixins.json"

[[dependencies.temp]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
    type="required"

[[dependencies.temp]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
    type="required"

